### ISSUE TITLE
Updating to Oculus Integration SDK v50

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unity-UltimateGloveBall#7] opened 2023-04-11 16:00 UTC
Project was currently on v46 and wanted to use some of the features of the latest SDK but on removing previous sdk and installing new one I am getting these errors - 

![image](https://user-images.githubusercontent.com/15714783/231221349-e90c5d5d-8281-415c-b0fa-abe3953911c3.png)

**Comment by AlexThiv** [comment] 2023-04-11 22:37
This is unfortunately caused by a change of the GUID of the platfrom.asmdef.meta
https://github.com/oculus-samples/Unity-UltimateGloveBall/blob/main/Assets/Oculus/Platform/Oculus.Platform.asmdef.meta, you will be able to resolve the issue by reverting the changes to the guid in this file. Which then will keep the reference in the other asmdef to be fixed.

**Comment by owlandfox** [comment] 2023-04-12 08:43
OK thanks that looks like it worked. Will we need to do this with each SDK update?

**Comment by AlexThiv** [comment] 2023-04-12 18:56
We are looking into resolving this issue for the future SDKs.

**Closed as completed by AlexThiv** 2023-04-12 18:56 UTC
