### ISSUE TITLE
Moving between in game UI and Oculusu platform UI is broken

### ISSUE THREAD

**Issue by owlandfox** [oculus-samples/Unity-UltimateGloveBall#3] opened 2023-03-30 09:16 UTC
How to reproduce -

1. When in game open up the menu to invite players to arena. 
2. Cancel to go back to in game UI
3. Oculus dashboard UI remains stuck until tapping Oculus button on controller to remove it
4. In game menu returns but responds to no button action to close it and return to game.

Is there any way to fix this as it just a broken user experience in what could be a very useful template otherwise. Thanks

**Comment by AlexThiv** [comment] 2023-03-30 17:55
Hi @owlandfox,
What OS Version are you on? There was some known issues when using v49 related to the Dashboard and returning to game, but they seem to be fixed in v50. I just tested out on v49, where I could reproduce the issue, and on v50 I didn't encounter these issues.

You can check your version on Settings->System->Software Update: Version and Runtime Version.
Can you validate if you have similar issues with the latest OS update?
Thanks for raising the issue.

**Comment by owlandfox** [comment] 2023-03-31 08:28
I can confirm that the issue still occurs on v50 but just to be clear there are two in game menus that appear - 

1. The world space one in the middle of the scene that appears when clicking "Invite friends" (This one works fine although still needs the explicit click on right controller oculus button to remove the oculus dashboard which doeesnt feel like expected behaviour)

2. The secondary one that appears when clicking the oculus menu button on left controller. Tapping "Players" here to open the roster and clickin on roster button to open Oculus platform. Now if trying to reverse out of here to get back to game sometimes you get locked on the menu or if you do manage to get out if it then player controls are locked and no movement is possible.

Check it out a couple times trying to get in and out of the player roster platform flow and youll see it is quite glitchy

**Comment by AlexThiv** [comment] 2023-06-23 17:37
We have fixed the issue where the controllers are unresponsive.
As for the need to click the oculus button to remove the dashboard this is currently by design. I would suggest raising the issue in the community forum (https://communityforums.atmeta.com/) I will also bring the question internally.
I will close this issue.

**Closed by AlexThiv** 2023-06-23 17:37 UTC
